import { StrategyTemplate } from "./types";

export const STRATEGY_TEMPLATES: StrategyTemplate[] = [
  // BULLISH
  {
    id: "BUY_CALL",
    name: "Buy Call",
    sentiment: "Bullish",
    description: "Max profit unlimited, risk limited to premium paid.",
    pathD: "M 3 23 L 13 23 L 29 5",
    builder: (spot, step, lotSize, expiry) => {
      const strike = Math.round(spot / step) * step;
      return [
        {
          legId: "leg-buy-call",
          symbol: `CALL-${strike}`,
          strike,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.019).toFixed(2)),
          iv: 18.1,
          ivOffset: 0.6,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "SELL_PUT",
    name: "Sell Put",
    sentiment: "Bullish",
    description: "Bullish to neutral. Earn premium if price stays above strike.",
    pathD: "M 3 23 L 17 7 L 29 7",
    builder: (spot, step, lotSize, expiry) => {
      const strike = Math.round(spot / step) * step - step;
      return [
        {
          legId: "leg-sell-put",
          symbol: `PUT-${strike}`,
          strike,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.015).toFixed(2)),
          iv: 19.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "BULL_CALL_SPREAD",
    name: "Bull Call Spread",
    sentiment: "Bullish",
    description: "Buy ATM Call and Sell OTM Call. Defined risk & defined reward.",
    pathD: "M 3 23 L 11 23 L 21 7 L 29 7",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "bcs-1",
          symbol: `CALL-${atm}`,
          strike: atm,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.022).toFixed(2)),
          iv: 18.1,
          ivOffset: 0.5,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "bcs-2",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.012).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "BULL_PUT_SPREAD",
    name: "Bull Put Spread",
    sentiment: "Bullish",
    description: "Sell higher strike Put, Buy lower strike Put for net credit.",
    pathD: "M 3 23 L 11 23 L 21 7 L 29 7",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "bps-1",
          symbol: `PUT-${atm - 2 * step}`,
          strike: atm - 2 * step,
          optionType: "PE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.008).toFixed(2)),
          iv: 19.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "bps-2",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.016).toFixed(2)),
          iv: 18.8,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "CALL_RATIO_BACK_SPREAD",
    name: "Call Ratio Back Spread",
    sentiment: "Bullish",
    description: "Sell 1 ATM Call, Buy 2 OTM Calls. Unlimited upside potential.",
    pathD: "M 3 16 L 12 16 L 20 26 L 29 4",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "crb-1",
          symbol: `CALL-${atm}`,
          strike: atm,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.022).toFixed(2)),
          iv: 18.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "crb-2",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "BUY",
          lots: 2,
          lotSize,
          price: Number((spot * 0.012).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "RANGE_FORWARD",
    name: "Range Forward",
    sentiment: "Bullish",
    description: "Collar structure: Sell OTM Put and Buy OTM Call for zero or low net debit.",
    pathD: "M 3 24 L 12 16 L 20 16 L 29 8",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "rf-1",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.014).toFixed(2)),
          iv: 18.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "rf-2",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.014).toFixed(2)),
          iv: 17.6,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "BUY_FUTURE",
    name: "Buy Future",
    sentiment: "Bullish",
    description: "Linear bullish exposure with futures leverage.",
    pathD: "M 4 26 L 28 6",
    builder: (spot, _step, lotSize, expiry) => {
      return [
        {
          legId: "bf-1",
          symbol: `FUT-${Math.round(spot)}`,
          strike: Math.round(spot),
          optionType: "FUT",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 1.002).toFixed(2)),
          iv: 0,
          ivOffset: 0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "LONG_SYNTHETIC_FUTURE",
    name: "Long Synthetic Future",
    sentiment: "Bullish",
    description: "Buy ATM Call + Sell ATM Put. Replicates a long future.",
    pathD: "M 4 26 L 28 6",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "lsf-1",
          symbol: `CALL-${atm}`,
          strike: atm,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.022).toFixed(2)),
          iv: 18.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "lsf-2",
          symbol: `PUT-${atm}`,
          strike: atm,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.021).toFixed(2)),
          iv: 18.2,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },

  // BEARISH
  {
    id: "BUY_PUT",
    name: "Buy Put",
    sentiment: "Bearish",
    description: "Substantial profit if underlying declines sharply.",
    pathD: "M 3 5 L 18 23 L 29 23",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "leg-buy-put",
          symbol: `PUT-${atm}`,
          strike: atm,
          optionType: "PE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.02).toFixed(2)),
          iv: 18.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "SELL_CALL",
    name: "Sell Call",
    sentiment: "Bearish",
    description: "Bearish to neutral income strategy with capped upside gain.",
    pathD: "M 3 7 L 16 7 L 29 23",
    builder: (spot, step, lotSize, expiry) => {
      const strike = Math.round(spot / step) * step + step;
      return [
        {
          legId: "leg-sell-call",
          symbol: `CALL-${strike}`,
          strike,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.014).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "BEAR_PUT_SPREAD",
    name: "Bear Put Spread",
    sentiment: "Bearish",
    description: "Buy ATM Put and Sell OTM Put for defined risk bear play.",
    pathD: "M 3 7 L 11 7 L 21 23 L 29 23",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "bearps-1",
          symbol: `PUT-${atm}`,
          strike: atm,
          optionType: "PE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.021).toFixed(2)),
          iv: 18.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "bearps-2",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.012).toFixed(2)),
          iv: 19.2,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "BEAR_CALL_SPREAD",
    name: "Bear Call Spread",
    sentiment: "Bearish",
    description: "Sell lower strike Call, Buy higher strike Call for net credit.",
    pathD: "M 3 7 L 11 7 L 21 23 L 29 23",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "bearcs-1",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.015).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "bearcs-2",
          symbol: `CALL-${atm + 2 * step}`,
          strike: atm + 2 * step,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.007).toFixed(2)),
          iv: 17.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },

  // NEUTRAL
  {
    id: "SHORT_STRADDLE",
    name: "Short Straddle",
    sentiment: "Neutral",
    description: "Sell ATM Call + Sell ATM Put. Max profit when price stays flat.",
    pathD: "M 3 24 L 16 6 L 29 24",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "ss-1",
          symbol: `CALL-${atm}`,
          strike: atm,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.022).toFixed(2)),
          iv: 18.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ss-2",
          symbol: `PUT-${atm}`,
          strike: atm,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.021).toFixed(2)),
          iv: 18.2,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "SHORT_STRANGLE",
    name: "Short Strangle",
    sentiment: "Neutral",
    description: "Sell OTM Call + Sell OTM Put. Wider profit zone than straddle.",
    pathD: "M 3 24 L 10 9 L 22 9 L 29 24",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "sst-1",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.014).toFixed(2)),
          iv: 19.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "sst-2",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.013).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "IRON_CONDOR",
    name: "Iron Condor",
    sentiment: "Neutral",
    description: "Defined risk range-bound play with hedged wings.",
    pathD: "M 3 21 L 9 21 L 14 7 L 18 7 L 23 21 L 29 21",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "ic-1",
          symbol: `PUT-${atm - 2 * step}`,
          strike: atm - 2 * step,
          optionType: "PE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.007).toFixed(2)),
          iv: 19.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ic-2",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.014).toFixed(2)),
          iv: 18.8,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ic-3",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.013).toFixed(2)),
          iv: 17.8,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ic-4",
          symbol: `CALL-${atm + 2 * step}`,
          strike: atm + 2 * step,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.006).toFixed(2)),
          iv: 17.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
  {
    id: "IRON_BUTTERFLY",
    name: "Iron Butterfly",
    sentiment: "Neutral",
    description: "Sell ATM straddle + Buy OTM wings for defined risk peak profit.",
    pathD: "M 3 21 L 10 21 L 16 6 L 22 21 L 29 21",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "ib-1",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.012).toFixed(2)),
          iv: 19.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ib-2",
          symbol: `PUT-${atm}`,
          strike: atm,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.021).toFixed(2)),
          iv: 18.2,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ib-3",
          symbol: `CALL-${atm}`,
          strike: atm,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.022).toFixed(2)),
          iv: 18.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "ib-4",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.012).toFixed(2)),
          iv: 17.5,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },

  // OTHERS
  {
    id: "JADE_LIZARD",
    name: "Jade Lizard",
    sentiment: "Others",
    description: "Sell OTM Put + Bear Call Spread. Zero upside risk when credit exceeds spread width.",
    pathD: "M 3 24 L 11 9 L 21 9 L 26 15 L 29 15",
    builder: (spot, step, lotSize, expiry) => {
      const atm = Math.round(spot / step) * step;
      return [
        {
          legId: "jl-1",
          symbol: `PUT-${atm - step}`,
          strike: atm - step,
          optionType: "PE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.015).toFixed(2)),
          iv: 18.8,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "jl-2",
          symbol: `CALL-${atm + step}`,
          strike: atm + step,
          optionType: "CE",
          action: "SELL",
          lots: 1,
          lotSize,
          price: Number((spot * 0.013).toFixed(2)),
          iv: 17.6,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
        {
          legId: "jl-3",
          symbol: `CALL-${atm + 2 * step}`,
          strike: atm + 2 * step,
          optionType: "CE",
          action: "BUY",
          lots: 1,
          lotSize,
          price: Number((spot * 0.006).toFixed(2)),
          iv: 17.0,
          ivOffset: 0.0,
          expiryDate: expiry,
          isEnabled: true,
        },
      ];
    },
  },
];
