"""Standalone Python Code Generator & Exporter Module for ShreeNexa Strategies.

Converts 4-part modular strategy configurations into self-contained, runnable
Python scripts utilizing the dhanhq SDK, pandas, and technical indicator libraries.
"""

from __future__ import annotations

import json
from typing import Any


class PythonCodeGenerator:
    """Generates standalone, runnable Python scripts from ShreeNexa Strategy JSON."""

    def __init__(self, strategy_config: dict[str, Any]) -> None:
        self.config = strategy_config
        self.strategy_type = str(strategy_config.get("strategy_type", "STOCK")).upper()
        self.name = str(strategy_config.get("name", "Standalone ShreeNexa Strategy"))
        self.version = int(strategy_config.get("version", 1))

        self.part1 = strategy_config.get("part_1_scope", {})
        self.part2 = strategy_config.get("part_2_entry", {})
        self.part3 = strategy_config.get("part_3_stoploss", {})
        self.part4 = strategy_config.get("part_4_exit", {})

    def generate(self) -> str:
        """Generate complete, standalone Python code."""
        header = self._generate_header()
        imports = self._generate_imports()
        broker_config = self._generate_broker_config()
        params = self._generate_parameters()
        indicators_helper = self._generate_indicator_helpers()
        condition_checker = self._generate_condition_checker()
        execution_helpers = self._generate_execution_helpers()
        main_loop = self._generate_main_loop()

        return "\n\n".join(
            [
                header,
                imports,
                broker_config,
                params,
                indicators_helper,
                condition_checker,
                execution_helpers,
                main_loop,
            ]
        )

    def _generate_header(self) -> str:
        safe_name = self.name.replace("\n", " ").strip()
        return f"""# ==============================================================================
# STRATEGY: {safe_name} (v{self.version})
# Type: {self.strategy_type}
# Generated by ShreeNexa Algo Engine (Standalone Exporter)
# Broker API: Dhan API v2 (dhanhq SDK)
# Target Environment: Python 3.10+ with pandas & dhanhq
# =============================================================================="""

    def _generate_imports(self) -> str:
        return """import datetime
import logging
import math
import sys
import time
from typing import Any, Dict, List, Optional

try:
    import pandas as pd
    import numpy as np
except ImportError:
    print("Please install pandas and numpy: pip install pandas numpy")
    sys.exit(1)

try:
    from dhanhq import dhanhq
except ImportError:
    print("Please install dhanhq SDK: pip install dhanhq")
    sys.exit(1)

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("strategy_execution.log", mode="a", encoding="utf-8")
    ]
)
logger = logging.getLogger(__name__)"""

    def _generate_broker_config(self) -> str:
        return """# --- BROKER CREDENTIALS ---
# Replace with your actual Dhan client credentials or set environment variables
CLIENT_ID = "YOUR_DHAN_CLIENT_ID"
ACCESS_TOKEN = "YOUR_DHAN_ACCESS_TOKEN"

try:
    dhan = dhanhq(CLIENT_ID, ACCESS_TOKEN)
    logger.info("Connected to Dhan API client.")
except Exception as e:
    logger.warning(f"Dhan client initialized in demo/offline mode: {e}")
    dhan = None"""

    def _generate_parameters(self) -> str:
        config_dump = json.dumps(self.config, indent=4)
        underlying = self.part1.get("underlying_symbol", "NIFTY")
        direction = self.part2.get("direction", "LONG")
        trigger_tf = self.part2.get("trigger_timeframe", "15min")
        sl_type = self.part3.get("sl_type", "PERCENTAGE")
        sl_val = self.part3.get("percentage_val", 20.0)

        return f'''# --- STRATEGY CONFIGURATION & CONSTANTS ---
STRATEGY_CONFIG = {config_dump}

STRATEGY_TYPE = "{self.strategy_type}"
UNDERLYING_SYMBOL = "{underlying}"
DIRECTION = "{direction}"
TRIGGER_TIMEFRAME = "{trigger_tf}"
STOPLOSS_TYPE = "{sl_type}"
STOPLOSS_VALUE = {sl_val}
'''

    def _generate_indicator_helpers(self) -> str:
        return '''# --- TECHNICAL INDICATOR CALCULATORS ---

def calculate_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """Calculate Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    avg_gain = gain.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1.0 / period, min_periods=period, adjust=False).mean()
    rs = avg_gain / avg_loss.replace(0, np.nan)
    return 100.0 - (100.0 / (1.0 + rs))


def calculate_ema(series: pd.Series, period: int = 20) -> pd.Series:
    """Calculate Exponential Moving Average (EMA)."""
    return series.ewm(span=period, adjust=False).mean()


def calculate_sma(series: pd.Series, period: int = 20) -> pd.Series:
    """Calculate Simple Moving Average (SMA)."""
    return series.rolling(window=period).mean()


def calculate_vwap(df: pd.DataFrame) -> pd.Series:
    """Calculate Volume Weighted Average Price (VWAP)."""
    typical_price = (df["high"] + df["low"] + df["close"]) / 3.0
    cum_vol_price = (typical_price * df["volume"]).cumsum()
    cum_vol = df["volume"].cumsum()
    return cum_vol_price / cum_vol.replace(0, np.nan)
'''

    def _generate_condition_checker(self) -> str:
        conditions = self.part2.get("conditions", [])
        logic = self.part2.get("logic", "AND").upper()

        code_lines = [
            "def check_entry_signals(spot_df: pd.DataFrame, "
            "option_df: Optional[pd.DataFrame] = None) -> bool:",
            '    """Evaluate Strategy Part 2 entry trigger conditions."""',
            "    if spot_df is None or len(spot_df) < 5:",
            "        return False",
            "",
            "    condition_results = []",
        ]

        if not conditions:
            code_lines.append("    return True  # No entry conditions defined")
        else:
            for idx, cond in enumerate(conditions, 1):
                pref = cond.get("price_reference", "SPOT").upper()
                df_name = "spot_df" if pref == "SPOT" else "option_df"
                indicator = cond.get("indicator")
                pattern = cond.get("pattern")
                operator = cond.get("operator", ">")
                val = cond.get("value")
                period = cond.get("period", 14)

                code_lines.append(f"    # Condition {idx}: {pref} {indicator or pattern}")
                if pref == "OPTION_PREMIUM":
                    code_lines.append(f"    if {df_name} is None or len({df_name}) < 2:")
                    code_lines.append("        return False")

                if pattern == "OPEN_EQ_HIGH":
                    code_lines.append(
                        f"    cond_{idx} = math.isclose({df_name}['open'].iloc[-1], "
                        f"{df_name}['high'].iloc[-1], rel_tol=1e-3)"
                    )
                elif pattern == "OPEN_EQ_LOW":
                    code_lines.append(
                        f"    cond_{idx} = math.isclose({df_name}['open'].iloc[-1], "
                        f"{df_name}['low'].iloc[-1], rel_tol=1e-3)"
                    )
                elif indicator == "RSI":
                    code_lines.append(
                        f"    rsi_{idx} = calculate_rsi({df_name}['close'], period={period})"
                    )
                    code_lines.append(f"    cond_{idx} = rsi_{idx}.iloc[-1] {operator} {val}")
                elif indicator == "EMA":
                    code_lines.append(
                        f"    ema_{idx} = calculate_ema({df_name}['close'], period={period})"
                    )
                    if operator == "close_above":
                        code_lines.append(
                            f"    cond_{idx} = {df_name}['close'].iloc[-1] > ema_{idx}.iloc[-1]"
                        )
                    elif operator == "close_below":
                        code_lines.append(
                            f"    cond_{idx} = {df_name}['close'].iloc[-1] < ema_{idx}.iloc[-1]"
                        )
                    else:
                        code_lines.append(
                            f"    cond_{idx} = {df_name}['close'].iloc[-1] {operator} {val}"
                        )
                else:
                    # Fallback condition check
                    code_lines.append(
                        f"    cond_{idx} = {df_name}['close'].iloc[-1] {operator} {val}"
                    )

                code_lines.append(f"    condition_results.append(cond_{idx})")
                code_lines.append("")

            if logic == "OR":
                code_lines.append("    return any(condition_results)")
            else:
                code_lines.append("    return all(condition_results)")

        return "\n".join(code_lines)

    def _generate_execution_helpers(self) -> str:
        return '''# --- ORDER EXECUTION & RISK MANAGEMENT ---

def place_order(
    security_id: str,
    exchange_segment: str,
    transaction_type: str,
    quantity: int,
    order_type: str = "MARKET",
    price: float = 0.0
) -> Dict[str, Any]:
    """Execute live or simulated order on Dhan."""
    logger.info(
        f"Placing Order: {transaction_type} {quantity} qty of {security_id} "
        f"({exchange_segment}) @ {order_type} {price}"
    )
    if dhan is not None:
        try:
            res = dhan.place_order(
                security_id=str(security_id),
                exchange_segment=exchange_segment,
                transaction_type=transaction_type,
                quantity=quantity,
                order_type=order_type,
                product_type="INTRADAY",
                price=price
            )
            logger.info(f"Dhan Order Response: {res}")
            return res
        except Exception as e:
            logger.error(f"Dhan order placement failed: {e}")
            return {"status": "ERROR", "message": str(e)}

    return {"status": "SIMULATED_SUCCESS", "order_id": "SIM_12345"}


def calculate_sl_and_targets(entry_price: float, direction: str = "LONG") -> Dict[str, Any]:
    """Calculate Stop-Loss and Target levels based on strategy Part 3 & 4."""
    sl_type = STRATEGY_CONFIG.get("part_3_stoploss", {}).get("sl_type", "PERCENTAGE")
    sl_pct = float(STRATEGY_CONFIG.get("part_3_stoploss", {}).get("percentage_val", 20.0) or 20.0)

    if direction == "LONG":
        sl_price = entry_price * (1.0 - (sl_pct / 100.0))
        target_1 = entry_price * 1.30  # Default 30% gain target
        target_2 = entry_price * 1.60  # Default 60% gain target
    else:
        sl_price = entry_price * (1.0 + (sl_pct / 100.0))
        target_1 = entry_price * 0.70
        target_2 = entry_price * 0.40

    return {
        "entry_price": entry_price,
        "stop_loss": sl_price,
        "target_1": target_1,
        "target_2": target_2,
    }
'''

    def _generate_main_loop(self) -> str:
        return '''# --- MAIN EXECUTION ENGINE ---

def run_strategy():
    """Main strategy execution loop."""
    logger.info(f"Starting {STRATEGY_TYPE} Strategy: {STRATEGY_CONFIG.get('name')}")
    in_position = False
    position_data = {}

    while True:
        try:
            now = datetime.datetime.now().time()
            session = STRATEGY_CONFIG.get("part_1_scope", {}).get("trading_session", {})
            start_str = session.get("start_time", "09:16:00")
            cutoff_str = session.get("no_new_entries_after", "14:30:00")
            square_off_str = session.get("force_square_off", "15:15:00")

            # Check square-off time
            if now.strftime("%H:%M:%S") >= square_off_str and in_position:
                logger.info("⏰ Force Square-off time reached. Closing positions...")
                in_position = False
                break

            # Polling market data & evaluating entry rules
            if not in_position and now.strftime("%H:%M:%S") <= cutoff_str:
                # In live mode, fetch real-time OHLCV DataFrame from Dhan API
                # Placeholder candle generation for standalone runner
                simulated_spot_df = pd.DataFrame({
                    "open": [24500.0, 24520.0, 24510.0, 24530.0, 24550.0],
                    "high": [24550.0, 24560.0, 24540.0, 24580.0, 24590.0],
                    "low": [24480.0, 24500.0, 24490.0, 24510.0, 24530.0],
                    "close": [24530.0, 24510.0, 24530.0, 24570.0, 24585.0],
                    "volume": [100000, 120000, 110000, 140000, 160000]
                })

                if check_entry_signals(simulated_spot_df):
                    logger.info("🎯 ENTRY SIGNAL TRIGGERED! Executing trade...")
                    levels = calculate_sl_and_targets(entry_price, DIRECTION)
                    sl_lvl = levels['stop_loss']
                    t1_lvl = levels['target_1']
                    logger.info(f"Entry: {entry_price} | SL: {sl_lvl} | T1: {t1_lvl}")
                    in_position = True
                    position_data = levels

            time.sleep(60)

        except KeyboardInterrupt:
            logger.info("Strategy execution stopped by user.")
            break
        except Exception as e:
            logger.error(f"Error in execution loop: {e}", exc_info=True)
            time.sleep(10)


if __name__ == "__main__":
    run_strategy()
'''


def export_strategy_python_script(strategy_config: dict[str, Any]) -> str:
    """Helper function to export a strategy JSON configuration to standalone Python code."""
    generator = PythonCodeGenerator(strategy_config)
    return generator.generate()
