"""Versioned Pydantic StrategyIR (Intermediate Representation) specification."""

from __future__ import annotations

import json
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class StrategyKind(StrEnum):
    """Execution category of the strategy."""

    STOCK = "stock"
    OPTION = "option"
    INVESTING = "investing"
    COMPOSITE = "composite"


class StrategyHorizon(StrEnum):
    """Trading time horizon used to select the grading band profile (§10.4.3)."""

    INTRADAY = "intraday"
    SWING = "swing"
    POSITIONAL = "positional"
    INVESTING = "investing"


class StrategyType(StrEnum):
    """Market style used to select the win-rate benchmark band (§10.4.4)."""

    TREND_FOLLOWING = "trend_following"
    SWING_TRADING = "swing_trading"
    MEAN_REVERSION = "mean_reversion"
    OPTION_SELLING = "option_selling"
    OTHER = "other"


class OrderSide(StrEnum):
    """Order trade side direction."""

    BUY = "BUY"
    SELL = "SELL"


class OptionType(StrEnum):
    """Derivative call / put option contract type."""

    CE = "CE"
    PE = "PE"


class CompareOp(StrEnum):
    """Relational comparison operators for signal conditions."""

    GT = ">"
    LT = "<"
    GTE = ">="
    LTE = "<="
    EQ = "=="
    NEQ = "!="


class InstrumentRef(BaseModel):
    """Reference to an exchange tradable instrument."""

    model_config = ConfigDict(extra="ignore")

    segment: str = Field(description="Exchange segment, e.g., NSE_EQ, NSE_FNO, IDX_I")
    security_id: str = Field(description="Security identifier or symbol code")
    symbol: str | None = Field(default=None, description="Human readable ticker symbol")


# --- Strike selectors ---


class ATMStrike(BaseModel):
    """At-the-money strike offset selector."""

    type: Literal["atm"] = "atm"
    offset: int = Field(default=0, description="Strike offset from ATM (e.g. 0, +1, -1)")


class DeltaStrike(BaseModel):
    """Delta-targeted strike selector."""

    type: Literal["delta"] = "delta"
    target: float = Field(ge=0.0, le=1.0, description="Target absolute delta (0.0 to 1.0)")


class PremiumStrike(BaseModel):
    """Target option premium price selector."""

    type: Literal["premium"] = "premium"
    target: float = Field(gt=0.0, description="Target premium value in currency units")


class AbsoluteStrike(BaseModel):
    """Fixed absolute strike price."""

    type: Literal["absolute"] = "absolute"
    strike: float = Field(gt=0.0, description="Exact strike price")


StrikeSelector = Annotated[
    ATMStrike | DeltaStrike | PremiumStrike | AbsoluteStrike,
    Field(discriminator="type"),
]


class ExpiryRule(BaseModel):
    """Option expiry selection specification."""

    model_config = ConfigDict(extra="ignore")

    type: Literal["weekly", "monthly", "exact"] = "weekly"
    offset: int = Field(default=0, ge=0, description="0 = nearest expiry, 1 = next")
    date: str | None = Field(default=None, description="Exact YYYY-MM-DD for exact expiry")


class OptionLegDef(BaseModel):
    """Definition of an individual option leg within a multi-leg structure."""

    model_config = ConfigDict(extra="ignore")

    id: str = Field(min_length=1, description="Unique leg identifier (e.g., ce, pe, leg1)")
    option_type: OptionType | Literal["CE", "PE"] = Field(description="Call (CE) or Put (PE)")
    strike: StrikeSelector = Field(description="Strike price selection rule")
    side: OrderSide | Literal["BUY", "SELL"] = Field(description="Trade side")
    lots: int = Field(default=1, gt=0, description="Number of standard contract lots")


# --- Universe Selectors ---


class StaticUniverse(BaseModel):
    """Fixed list of pre-selected instruments."""

    type: Literal["static"] = "static"
    instruments: list[InstrumentRef] = Field(min_length=1, description="Explicit instrument list")


class WatchlistUniverse(BaseModel):
    """Dynamic universe sourced from a saved user watchlist."""

    type: Literal["watchlist"] = "watchlist"
    watchlist_id: int = Field(gt=0, description="Database ID of the watchlist")


class ScreenerUniverse(BaseModel):
    """Dynamic universe generated by scheduled screener executions."""

    type: Literal["screener"] = "screener"
    screener_id: int = Field(gt=0, description="Database ID of the screener definition")
    refresh: Literal["daily", "hourly", "every_bar"] = Field(
        default="daily", description="Membership refresh frequency"
    )


class IndexUniverse(BaseModel):
    """Point-in-time constituent universe for a major index (e.g. NIFTY 50)."""

    type: Literal["index"] = "index"
    index_name: str = Field(min_length=1, description="Official index name")


class OptionLegsUniverse(BaseModel):
    """Multi-leg option strategy universe derived from an underlying asset."""

    type: Literal["option_legs"] = "option_legs"
    underlying: InstrumentRef = Field(description="Underlying equity or index reference")
    expiry_rule: ExpiryRule = Field(
        default_factory=ExpiryRule, description="Expiry determination policy"
    )
    legs: list[OptionLegDef] = Field(min_length=1, description="Option legs composing strategy")


UniverseSelector = Annotated[
    StaticUniverse | WatchlistUniverse | ScreenerUniverse | IndexUniverse | OptionLegsUniverse,
    Field(discriminator="type"),
]


class SessionConfig(BaseModel):
    """Trading session and calendar boundaries."""

    model_config = ConfigDict(extra="ignore")

    segment: str = Field(default="NSE_EQ", description="Market segment calendar identifier")
    timezone: str = Field(default="Asia/Kolkata", description="IANA Timezone name")


class IndicatorDef(BaseModel):
    """Declaration of a technical indicator primitive or formula node."""

    model_config = ConfigDict(extra="ignore")

    fn: str = Field(description="Indicator primitive name (e.g. RSI, EMA) or 'custom'")
    params: dict[str, Any] = Field(
        default_factory=dict, description="Parameter dictionary passed to indicator"
    )
    source: str | None = Field(default="close", description="Input price column series")
    indicator_def_id: int | None = Field(
        default=None, description="Reference to custom indicator_def ID"
    )


# --- Signal Grammar and Operands ---


class FieldOperand(BaseModel):
    """Reference to standard price/volume bar field."""

    field: str = Field(description="Column name e.g., open, high, low, close, volume, oi")


class RefOperand(BaseModel):
    """Reference to declared indicator instance."""

    ref: str = Field(description="Indicator instance identifier key")


class ConstOperand(BaseModel):
    """Constant scalar literal operand."""

    const: float | int | bool | str = Field(description="Scalar literal value")


OperandRef = (
    FieldOperand | RefOperand | ConstOperand | dict[str, Any] | float | int | str
)


class LevelRef(BaseModel):
    """Price level anchor reference."""

    model_config = ConfigDict(extra="ignore")

    ref: str | None = Field(default=None, description="Named indicator or level ref")
    type: str | None = Field(default=None, description="prior_high, prev_day_high, orh, etc.")
    minutes: int | None = Field(default=None, description="Opening range minutes duration")
    bars: int | None = Field(default=None, description="Prior N bars lookback")


# --- Signal Nodes (Recursive AST) ---


class AndNode(BaseModel):
    """Boolean AND conjunction node."""

    node: Literal["And"] = "And"
    children: list[SignalNode] = Field(min_length=1)


class OrNode(BaseModel):
    """Boolean OR disjunction node."""

    node: Literal["Or"] = "Or"
    children: list[SignalNode] = Field(min_length=1)


class NotNode(BaseModel):
    """Boolean NOT negation node."""

    node: Literal["Not"] = "Not"
    child: SignalNode


class PriceLevelBreakNode(BaseModel):
    """Breakout of a key price level optionally gated by a preceding condition."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["PriceLevelBreak"] = "PriceLevelBreak"
    level: LevelRef | str | dict[str, Any] = Field(description="Reference level descriptor")
    direction: Literal["above", "below"] = Field(default="above", description="Breakout direction")
    after: SignalNode | None = Field(
        default=None, description="Gating condition that must hold prior to the break"
    )


class SequenceNode(BaseModel):
    """Ordered multi-step condition sequence within a maximum bar window."""

    node: Literal["Sequence"] = "Sequence"
    steps: list[SignalNode] = Field(min_length=2, description="Ordered condition steps")
    within: int = Field(gt=0, description="Max bar duration for the sequence to complete")


class TimeWindowNode(BaseModel):
    """Time-based execution gating condition."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    node: Literal["TimeWindow"] = "TimeWindow"
    mode: Literal["clock", "from_open", "to_close", "dte"] = Field(
        default="clock", description="Time window comparison mode"
    )
    from_time: str | None = Field(
        default=None, alias="from", description="Window start (HH:MM or minutes)"
    )
    to_time: str | None = Field(
        default=None, alias="to", description="Window end (HH:MM or minutes)"
    )
    dte: int | None = Field(default=None, description="Days to expiry filter")


class IndicatorCompareNode(BaseModel):
    """Relational comparison between two operands."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["IndicatorCompare"] = "IndicatorCompare"
    left: OperandRef
    op: CompareOp | str = Field(description="Relational comparison operator")
    right: OperandRef


class CrossOverNode(BaseModel):
    """Strict upward crossover (left crosses above right on the current bar)."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["CrossOver"] = "CrossOver"
    left: OperandRef
    right: OperandRef


class CrossUnderNode(BaseModel):
    """Strict downward crossunder (left crosses below right on the current bar)."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["CrossUnder"] = "CrossUnder"
    left: OperandRef
    right: OperandRef


class PctChangeNode(BaseModel):
    """Percentage rate of change comparison over N bars."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["PctChange"] = "PctChange"
    source: str = Field(default="close", description="Price series name")
    lookback: int = Field(gt=0, description="Lookback bars")
    op: CompareOp | str = Field(description="Relational comparison operator")
    value: float = Field(description="Target percentage move threshold")


class PersistNode(BaseModel):
    """Condition that must evaluate to True for N consecutive bars."""

    node: Literal["Persist"] = "Persist"
    child: SignalNode
    bars: int = Field(gt=0, description="Consecutive bar count")


class StrategySignalNode(BaseModel):
    """Signal composition referencing another strategy's signal."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["StrategySignal"] = "StrategySignal"
    strategy_id: int | str = Field(description="Referenced strategy ID or name")
    signal: str = Field(default="entry", description="Signal identifier (e.g. entry, exit)")


class RegimeNode(BaseModel):
    """Market regime filter condition."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["Regime"] = "Regime"
    detector: str = Field(description="Regime detector model identifier")
    state: str = Field(description="Required regime state label (e.g. trending_up, volatile)")


class CustomPythonNode(BaseModel):
    """Sandboxed custom Python calculation escape hatch."""

    model_config = ConfigDict(extra="ignore")

    node: Literal["CustomPython"] = "CustomPython"
    ref: str = Field(description="Custom python module or code reference")


SignalNode = Annotated[
    AndNode
    | OrNode
    | NotNode
    | PriceLevelBreakNode
    | SequenceNode
    | TimeWindowNode
    | IndicatorCompareNode
    | CrossOverNode
    | CrossUnderNode
    | PctChangeNode
    | PersistNode
    | StrategySignalNode
    | RegimeNode
    | CustomPythonNode,
    Field(discriminator="node"),
]

# Rebuild recursive models
AndNode.model_rebuild()
OrNode.model_rebuild()
NotNode.model_rebuild()
PriceLevelBreakNode.model_rebuild()
SequenceNode.model_rebuild()
PersistNode.model_rebuild()


# --- Rules and Actions ---


class EntryRule(BaseModel):
    """Trade entry rule specification."""

    model_config = ConfigDict(extra="ignore")

    id: str = Field(min_length=1, description="Unique entry identifier")
    side: OrderSide | Literal["BUY", "SELL"] = Field(
        default=OrderSide.BUY, description="Trade side"
    )
    when: SignalNode = Field(description="Signal tree condition that triggers entry")


class ExitRule(BaseModel):
    """Trade exit and stop-loss / take-profit rule."""

    model_config = ConfigDict(extra="ignore")

    id: str = Field(min_length=1, description="Unique exit identifier")
    type: Literal["target", "stop", "time", "signal", "trailing_stop"] = Field(
        description="Exit category"
    )
    pct: float | None = Field(default=None, gt=0.0, description="Percentage threshold")
    at: str | None = Field(default=None, description="Time of day exit (e.g. 15:15)")
    when: SignalNode | None = Field(default=None, description="Signal condition for signal exit")
    trailing_pct: float | None = Field(default=None, gt=0.0, description="Trailing stop percentage")


class SizingRule(BaseModel):
    """Position sizing policy."""

    model_config = ConfigDict(extra="ignore")

    type: Literal[
        "fixed_qty", "fixed_value", "pct_capital", "risk_pct", "lots", "kelly_fraction"
    ] = "pct_capital"
    qty: int | None = Field(default=None, gt=0, description="Fixed share quantity")
    value: float | None = Field(default=None, gt=0.0, description="Fixed currency value")
    pct: float | None = Field(default=100.0, gt=0.0, le=100.0, description="Percent of capital")
    risk_pct: float | None = Field(
        default=None, gt=0.0, le=100.0, description="Risk budget percentage"
    )
    stop_ref: str | None = Field(default=None, description="Stop exit rule ID used for risk sizing")
    lots: int | None = Field(default=None, gt=0, description="Derivatives lot count")
    cap: float | None = Field(default=None, gt=0.0, description="Maximum fraction cap for Kelly")


class RiskRule(BaseModel):
    """Strategy-level risk parameters and trade limits."""

    model_config = ConfigDict(extra="ignore")

    max_positions: int = Field(default=5, ge=1, description="Maximum concurrent open positions")
    max_daily_loss_pct: float | None = Field(
        default=None, gt=0.0, description="Maximum daily drawdown percentage"
    )
    max_daily_loss_abs: float | None = Field(
        default=None, gt=0.0, description="Maximum daily loss in currency units"
    )
    max_position_value_pct: float | None = Field(
        default=None, gt=0.0, le=100.0, description="Maximum capital allocated per position"
    )
    no_trade_windows: list[str] = Field(
        default_factory=list, description="Restricted time windows (e.g. ['09:15-09:20'])"
    )
    max_trades_per_day: int | None = Field(
        default=None, ge=1, description="Maximum allowed orders per trading day"
    )


# --- Top-Level StrategyIR ---


class StrategyIR(BaseModel):
    """Versioned Strategy Intermediate Representation (IR).

    The single canonical specification shared across screener, backtester,
    paper trading, live execution, and AI generation.
    """

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    ir_version: int = Field(default=1, ge=1, description="IR schema specification version")
    name: str = Field(min_length=1, description="Strategy name")
    kind: StrategyKind = Field(description="Trading domain kind (stock, option, etc.)")
    horizon: StrategyHorizon = Field(
        description="Time horizon selecting the grading band profile (§10.4.3)"
    )
    strategy_type: StrategyType = Field(
        description="Market archetype selecting the win-rate benchmark band (§10.4.4)"
    )
    universe: UniverseSelector = Field(description="Instrument universe selector")
    timeframe: str = Field(default="5m", description="Base operational timeframe (e.g. 1m, 5m, 1d)")
    session: SessionConfig = Field(
        default_factory=SessionConfig, description="Calendar and session boundaries"
    )
    indicators: dict[str, IndicatorDef] = Field(
        default_factory=dict, description="Declared technical indicators"
    )
    entries: list[EntryRule] = Field(
        default_factory=list, description="Trade entry rule conditions"
    )
    exits: list[ExitRule] = Field(default_factory=list, description="Exit and stop rules")
    sizing: SizingRule = Field(default_factory=SizingRule, description="Position sizing model")
    risk: RiskRule = Field(default_factory=RiskRule, description="Strategy risk thresholds")

    def to_dict(self) -> dict[str, Any]:
        """Serialize model to clean dictionary representation."""
        return self.model_dump(by_alias=True, exclude_none=True)

    def to_json(self, indent: int = 2) -> str:
        """Serialize model to formatted JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> StrategyIR:
        """Parse StrategyIR from raw dictionary."""
        return cls.model_validate(data)

    @classmethod
    def from_json(cls, json_str: str) -> StrategyIR:
        """Parse StrategyIR from JSON string."""
        return cls.model_validate_json(json_str)


def export_strategy_ir_json_schema() -> dict[str, Any]:
    """Export complete JSON Schema for the StrategyIR model."""
    return StrategyIR.model_json_schema()
