"""Feature-builder pipeline package (Epic 11)."""

from __future__ import annotations

from app.feature_builder.gates import (
    FailureCategory,
    FilteredFailureSummary,
    GateExecutionSummary,
    GateHarness,
    GateResult,
    GateStatus,
    GateType,
    RetryPolicy,
    gate_harness,
)
from app.feature_builder.models import (
    FeatureRequest,
    FeatureSpec,
    FeatureSpecUpdate,
    RiskLevel,
    SpecApprovalDecision,
    SpecStatus,
)
from app.feature_builder.runner import (
    CodexAuthenticationError,
    CodexQuotaExceededError,
    CodexTaskRunner,
    RunnerTaskStatus,
    TaskEvent,
    TaskEventType,
    TaskExecutionError,
    TaskJournalState,
    TaskStartRequest,
    TaskStep,
    task_runner,
)
from app.feature_builder.security import (
    DiffGuard,
    EnforcementLayer,
    LayeredSecurityEngine,
    PromotionGuard,
    PromptGuard,
    ProtectedPathAuditLogger,
    ProtectedPathViolationError,
    SecurityAuditAction,
    SecurityAuditEvent,
    ToolGuard,
    audit_logger,
    is_protected_path,
    security_engine,
)
from app.feature_builder.spec import (
    PROTECTED_PATHS,
    FeatureSpecEngine,
    evaluate_ambiguity,
    evaluate_request_risk,
    spec_engine,
)
from app.feature_builder.worktree import (
    PathEscapeViolationError,
    WorktreeAllocation,
    WorktreeCreateRequest,
    WorktreeManager,
    safe_write_worktree_file,
    validate_worktree_path,
    worktree_manager,
)

__all__ = [
    "PROTECTED_PATHS",
    "CodexAuthenticationError",
    "CodexQuotaExceededError",
    "CodexTaskRunner",
    "DiffGuard",
    "EnforcementLayer",
    "FailureCategory",
    "FeatureRequest",
    "FeatureSpec",
    "FeatureSpecEngine",
    "FeatureSpecUpdate",
    "FilteredFailureSummary",
    "GateExecutionSummary",
    "GateHarness",
    "GateResult",
    "GateStatus",
    "GateType",
    "LayeredSecurityEngine",
    "PathEscapeViolationError",
    "PromotionGuard",
    "PromptGuard",
    "ProtectedPathAuditLogger",
    "ProtectedPathViolationError",
    "RetryPolicy",
    "RiskLevel",
    "RunnerTaskStatus",
    "SecurityAuditAction",
    "SecurityAuditEvent",
    "SpecApprovalDecision",
    "SpecStatus",
    "TaskEvent",
    "TaskEventType",
    "TaskExecutionError",
    "TaskJournalState",
    "TaskStartRequest",
    "TaskStep",
    "ToolGuard",
    "WorktreeAllocation",
    "WorktreeCreateRequest",
    "WorktreeManager",
    "audit_logger",
    "evaluate_ambiguity",
    "evaluate_request_risk",
    "gate_harness",
    "is_protected_path",
    "safe_write_worktree_file",
    "security_engine",
    "spec_engine",
    "task_runner",
    "validate_worktree_path",
    "worktree_manager",
]
