"""feedd: owns Dhan market-feed/depth connections (per ADR-0002)."""

from app.feedd.budget import (
    BudgetStatus,
    ConnectionBudgetConfig,
    ConnectionBudgetExhaustedError,
    ConnectionBudgetManager,
    ConnectionLease,
    PoolMode,
    SocketType,
    get_connection_budget_manager,
    load_budget_config,
)
from app.feedd.cache import (
    CACHE_SCHEMA_VERSION,
    CachedDepth,
    CachedDepthLevel,
    CachedFeedHealth,
    CachedOI,
    CachedQuote,
    HotCache,
    InMemoryHotCache,
    RedisHotCache,
    depth_key,
    health_key,
    oi_key,
    quote_key,
)
from app.feedd.subscriptions import (
    MAX_INSTRUMENTS_PER_MESSAGE,
    MAX_INSTRUMENTS_PER_SOCKET,
    FeedSocketRecord,
    InstrumentKey,
    SubscriptionCapacityExceededError,
    SubscriptionItem,
    SubscriptionManager,
    SubscriptionMode,
    SubscriptionPriority,
)

__all__ = [
    "CACHE_SCHEMA_VERSION",
    "MAX_INSTRUMENTS_PER_MESSAGE",
    "MAX_INSTRUMENTS_PER_SOCKET",
    "BudgetStatus",
    "CachedDepth",
    "CachedDepthLevel",
    "CachedFeedHealth",
    "CachedOI",
    "CachedQuote",
    "ConnectionBudgetConfig",
    "ConnectionBudgetExhaustedError",
    "ConnectionBudgetManager",
    "ConnectionLease",
    "FeedSocketRecord",
    "HotCache",
    "InMemoryHotCache",
    "InstrumentKey",
    "PoolMode",
    "RedisHotCache",
    "SocketType",
    "SubscriptionCapacityExceededError",
    "SubscriptionItem",
    "SubscriptionManager",
    "SubscriptionMode",
    "SubscriptionPriority",
    "depth_key",
    "get_connection_budget_manager",
    "health_key",
    "load_budget_config",
    "oi_key",
    "quote_key",
]
