"""Engine contracts and state machine models for clocks, data sources, brokers, and portfolios."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any, Protocol, runtime_checkable

from pydantic import BaseModel, ConfigDict, Field

from app.warehouse.schema import BarRecord


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    SL = "SL"
    SL_M = "SL_M"


class TimeInForce(StrEnum):
    DAY = "DAY"
    IOC = "IOC"
    GTC = "GTC"


class OrderStatus(StrEnum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    FILLED = "FILLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class OrderRequest(BaseModel):
    """Execution order request specification."""

    model_config = ConfigDict(extra="forbid")

    order_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    security_id: str
    exchange_segment: str
    side: OrderSide
    quantity: int = Field(gt=0, description="Order quantity in units (must be positive)")
    order_type: OrderType = Field(default=OrderType.MARKET)
    price: float | None = Field(default=None, description="Limit price for LIMIT/SL orders")
    trigger_price: float | None = Field(
        default=None, description="Trigger price for SL/SL_M orders"
    )
    time_in_force: TimeInForce = Field(default=TimeInForce.DAY)
    tag: str | None = Field(default=None, description="Client/Strategy attribution tag")
    created_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class OrderResult(BaseModel):
    """Broker order submission response."""

    model_config = ConfigDict(extra="forbid")

    order_id: str
    status: OrderStatus
    reason: str | None = None
    submitted_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class FillEvent(BaseModel):
    """Trade execution fill event with transaction costs."""

    model_config = ConfigDict(extra="forbid")

    fill_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    order_id: str
    security_id: str
    exchange_segment: str
    side: OrderSide
    quantity: int = Field(gt=0)
    price: float = Field(ge=0.0)
    timestamp: datetime
    brokerage: float = Field(default=0.0, ge=0.0)
    taxes: float = Field(default=0.0, ge=0.0)
    slippage: float = Field(default=0.0, ge=0.0)

    @property
    def total_cost(self) -> float:
        """Total frictional cost (brokerage + taxes + slippage)."""
        return self.brokerage + self.taxes + self.slippage


class Position(BaseModel):
    """Tracked asset position state with mark-to-market and realized PnL calculations."""

    model_config = ConfigDict(extra="forbid")

    security_id: str
    exchange_segment: str
    quantity: int = Field(default=0, description="Positive=Long, Negative=Short, 0=Flat")
    average_price: float = Field(default=0.0, ge=0.0)
    realized_pnl: float = Field(default=0.0)
    unrealized_pnl: float = Field(default=0.0)
    current_price: float = Field(default=0.0, ge=0.0)

    def apply_fill(self, side: OrderSide, qty: int, price: float) -> float:
        """Apply a fill to the position state and return the realized PnL generated by this fill."""
        if qty <= 0:
            return 0.0

        pnl_generated = 0.0
        current_qty = self.quantity
        avg_price = self.average_price

        if side == OrderSide.BUY:
            if current_qty >= 0:
                # Adding to Long position
                new_qty = current_qty + qty
                self.average_price = (
                    (current_qty * avg_price + qty * price) / new_qty if new_qty > 0 else 0.0
                )
                self.quantity = new_qty
            else:
                # Covering Short position
                abs_short = abs(current_qty)
                if qty <= abs_short:
                    pnl_generated = qty * (avg_price - price)
                    self.quantity = current_qty + qty
                    if self.quantity == 0:
                        self.average_price = 0.0
                else:
                    # Partial cover + flip to Long
                    covered_qty = abs_short
                    flipped_long_qty = qty - abs_short
                    pnl_generated = covered_qty * (avg_price - price)
                    self.quantity = flipped_long_qty
                    self.average_price = price
        else:  # OrderSide.SELL
            if current_qty <= 0:
                # Adding to Short position
                abs_short = abs(current_qty)
                new_abs = abs_short + qty
                self.average_price = (
                    (abs_short * avg_price + qty * price) / new_abs if new_abs > 0 else 0.0
                )
                self.quantity = -new_abs
            else:
                # Closing Long position
                if qty <= current_qty:
                    pnl_generated = qty * (price - avg_price)
                    self.quantity = current_qty - qty
                    if self.quantity == 0:
                        self.average_price = 0.0
                else:
                    # Partial close + flip to Short
                    closed_qty = current_qty
                    flipped_short_qty = qty - current_qty
                    pnl_generated = closed_qty * (price - avg_price)
                    self.quantity = -flipped_short_qty
                    self.average_price = price

        self.realized_pnl += pnl_generated
        self.update_price(price)
        return pnl_generated

    def update_price(self, price: float) -> None:
        """Update current market price and compute unrealized PnL."""
        self.current_price = price
        if self.quantity > 0:
            self.unrealized_pnl = self.quantity * (price - self.average_price)
        elif self.quantity < 0:
            self.unrealized_pnl = abs(self.quantity) * (self.average_price - price)
        else:
            self.unrealized_pnl = 0.0


class EquityPoint(BaseModel):
    """Point on the portfolio equity curve."""

    model_config = ConfigDict(extra="forbid")

    timestamp: datetime
    equity: float
    cash: float
    unrealized_pnl: float
    realized_pnl: float


class Portfolio(BaseModel):
    """Portfolio accounting state machine tracking cash, positions, and equity curve."""

    model_config = ConfigDict(extra="forbid")

    initial_cash: float = Field(gt=0.0)
    cash: float
    positions: dict[str, Position] = Field(default_factory=dict)
    fills: list[FillEvent] = Field(default_factory=list)
    equity_curve: list[EquityPoint] = Field(default_factory=list)

    @classmethod
    def create(cls, initial_cash: float) -> Portfolio:
        """Factory for new Portfolio."""
        return cls(
            initial_cash=initial_cash,
            cash=initial_cash,
            positions={},
            fills=[],
            equity_curve=[],
        )

    def apply_fill(self, fill: FillEvent) -> None:
        """Apply trade execution fill to portfolio cash and asset positions."""
        total_trade_value = fill.quantity * fill.price
        total_costs = fill.total_cost

        if fill.side == OrderSide.BUY:
            self.cash -= total_trade_value + total_costs
        else:
            self.cash += total_trade_value - total_costs

        if fill.security_id not in self.positions:
            self.positions[fill.security_id] = Position(
                security_id=fill.security_id,
                exchange_segment=fill.exchange_segment,
                quantity=0,
                average_price=0.0,
                current_price=fill.price,
            )

        pos = self.positions[fill.security_id]
        pos.apply_fill(fill.side, fill.quantity, fill.price)
        self.fills.append(fill)

    def mark_to_market(self, prices: dict[str, float], timestamp: datetime) -> float:
        """Update mark-to-market prices for all positions and record equity snapshot."""
        for sec_id, price in prices.items():
            if sec_id in self.positions:
                self.positions[sec_id].update_price(price)

        total_unrealized = sum(p.unrealized_pnl for p in self.positions.values())
        total_realized = sum(p.realized_pnl for p in self.positions.values())

        # Net liquidation value: initial_cash + realized + unrealized - total_costs
        total_costs = sum(f.total_cost for f in self.fills)
        total_equity = self.initial_cash + total_realized + total_unrealized - total_costs

        self.equity_curve.append(
            EquityPoint(
                timestamp=timestamp,
                equity=total_equity,
                cash=self.cash,
                unrealized_pnl=total_unrealized,
                realized_pnl=total_realized,
            )
        )
        return total_equity

    def total_equity(self) -> float:
        """Get latest total equity value."""
        if self.equity_curve:
            return self.equity_curve[-1].equity
        return self.cash

    def get_state(self) -> dict[str, Any]:
        """Serialize complete portfolio state."""
        return self.model_dump(mode="json")

    @classmethod
    def restore_state(cls, state: dict[str, Any]) -> Portfolio:
        """Restore portfolio from serialized dictionary."""
        return cls.model_validate(state)


@runtime_checkable
class Clock(Protocol):
    """Abstract clock interface providing execution time."""

    def now(self) -> datetime:
        """Current timestamp."""
        ...

    def is_done(self) -> bool:
        """Whether the clock sequence has finished."""
        ...


class SimClock:
    """Discrete simulation clock stepping through historical timestamps."""

    def __init__(self, timestamps: list[datetime]) -> None:
        if not timestamps:
            raise ValueError("SimClock requires at least one timestamp")
        self._timestamps = sorted(timestamps)
        self._index = 0

    def now(self) -> datetime:
        """Current simulation timestamp."""
        return self._timestamps[self._index]

    def step(self) -> datetime | None:
        """Advance to next simulation timestamp; returns None when completed."""
        if self._index + 1 < len(self._timestamps):
            self._index += 1
            return self.now()
        return None

    def is_done(self) -> bool:
        """True when all timestamps in simulation have elapsed."""
        return self._index >= len(self._timestamps) - 1

    def get_state(self) -> dict[str, Any]:
        """Serialize SimClock state."""
        return {
            "index": self._index,
            "timestamps": [t.isoformat() for t in self._timestamps],
        }

    @classmethod
    def restore_state(cls, state: dict[str, Any]) -> SimClock:
        """Restore SimClock state."""
        timestamps = [datetime.fromisoformat(t) for t in state["timestamps"]]
        clock = cls(timestamps)
        clock._index = state["index"]
        return clock


class RealClock:
    """Live system clock returning current UTC time."""

    def now(self) -> datetime:
        """Current UTC timestamp."""
        return datetime.now(tz=UTC)

    def is_done(self) -> bool:
        """RealClock is perpetual."""
        return False


@runtime_checkable
class DataSource(Protocol):
    """Abstract market data source protocol."""

    def advance(self, now: datetime) -> list[BarRecord]:
        """Retrieve new bars as-of timestamp `now`."""
        ...


class HistoricalDataSource:
    """Historical bar replay data source ensuring zero forward lookahead."""

    def __init__(self, bars: list[BarRecord]) -> None:
        # Group and sort bars chronologically per security
        self._bars = sorted(bars, key=lambda b: b.timestamp)
        self._pointers: dict[str, int] = {}
        self._bars_by_sec: dict[str, list[BarRecord]] = {}
        for b in self._bars:
            self._bars_by_sec.setdefault(b.security_id, []).append(b)
            self._pointers[b.security_id] = 0

    def advance(self, now: datetime) -> list[BarRecord]:
        """Emit bars with timestamp == now."""
        current_bars: list[BarRecord] = []
        for sec_id, sec_bars in self._bars_by_sec.items():
            ptr = self._pointers[sec_id]
            while ptr < len(sec_bars) and sec_bars[ptr].timestamp <= now:
                if sec_bars[ptr].timestamp == now:
                    current_bars.append(sec_bars[ptr])
                ptr += 1
            self._pointers[sec_id] = ptr
        return current_bars

    def get_history(self, security_id: str, until: datetime, count: int) -> list[BarRecord]:
        """Get past `count` bars up to and including `until` without lookahead."""
        sec_bars = self._bars_by_sec.get(security_id, [])
        eligible = [b for b in sec_bars if b.timestamp <= until]
        return eligible[-count:] if count > 0 else eligible

    def get_state(self) -> dict[str, Any]:
        """Serialize data source playback position."""
        return {"pointers": dict(self._pointers)}

    def restore_state(self, state: dict[str, Any]) -> None:
        """Restore playback pointers."""
        self._pointers = dict(state["pointers"])


@runtime_checkable
class Broker(Protocol):
    """Abstract broker interface for order execution and position query."""

    def submit(self, orders: list[OrderRequest]) -> list[OrderResult]:
        """Submit order requests for execution."""
        ...

    def cancel(self, order_id: str) -> bool:
        """Cancel active pending order."""
        ...

    def get_positions(self) -> dict[str, Position]:
        """Retrieve current broker positions."""
        ...

    def get_account_balance(self) -> float:
        """Retrieve available cash balance."""
        ...


class EngineCheckpoint(BaseModel):
    """Durable snapshot of complete execution engine state."""

    model_config = ConfigDict(extra="forbid")

    checkpoint_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: datetime
    step_index: int
    clock_state: dict[str, Any]
    datasource_state: dict[str, Any]
    portfolio_state: dict[str, Any]
    strategy_state: dict[str, Any] = Field(default_factory=dict)
