"""Dhan integration package for ShreeNexa."""

from app.dhan.client import DhanRestClient
from app.dhan.credentials import (
    DhanCredentials,
    clear_dhan_credentials_dpapi,
    resolve_dhan_credentials,
    store_dhan_credentials_dpapi,
)
from app.dhan.exceptions import (
    DhanAuthenticationError,
    DhanClientError,
    DhanError,
    DhanMalformedResponseError,
    DhanRateLimitError,
    DhanServerError,
    DhanTimeoutError,
)
from app.dhan.health import DhanTokenHealth, check_token_health
from app.dhan.instruments import (
    IngestSummary,
    InstrumentRecord,
    InstrumentSearchQuery,
    get_distinct_segments,
    get_expiries_for_underlying,
    get_instrument,
    get_option_chain_instruments,
    ingest_instruments,
    instrument_table,
    parse_scrip_master_csv,
    resolve_exchange_segment,
    search_instruments,
)
from app.dhan.limiter import (
    InMemoryTokenBucket,
    RedisTokenBucket,
    TokenBucket,
    get_dhan_rate_limiter,
)
from app.dhan.limits_config import (
    BackoffSpec,
    DhanLimitsConfig,
    RateLimitSpec,
    get_category_for_endpoint,
    load_dhan_limits,
)
from app.dhan.models import (
    DhanFundLimit,
    DhanHistoricalBar,
    DhanHistoricalData,
    DhanHolding,
    DhanPosition,
    DhanProfile,
    DhanQuote,
    DhanResponseEnvelope,
)
from app.dhan.transport import (
    CassetteTransport,
    DhanTransport,
    HTTPTransport,
    MockTransport,
)

__all__ = [
    "BackoffSpec",
    "CassetteTransport",
    "DhanAuthenticationError",
    "DhanClientError",
    "DhanCredentials",
    "DhanError",
    "DhanFundLimit",
    "DhanHistoricalBar",
    "DhanHistoricalData",
    "DhanHolding",
    "DhanLimitsConfig",
    "DhanMalformedResponseError",
    "DhanPosition",
    "DhanProfile",
    "DhanQuote",
    "DhanRateLimitError",
    "DhanResponseEnvelope",
    "DhanRestClient",
    "DhanServerError",
    "DhanTimeoutError",
    "DhanTokenHealth",
    "DhanTransport",
    "HTTPTransport",
    "InMemoryTokenBucket",
    "IngestSummary",
    "InstrumentRecord",
    "InstrumentSearchQuery",
    "MockTransport",
    "RateLimitSpec",
    "RedisTokenBucket",
    "TokenBucket",
    "check_token_health",
    "clear_dhan_credentials_dpapi",
    "get_category_for_endpoint",
    "get_dhan_rate_limiter",
    "get_distinct_segments",
    "get_expiries_for_underlying",
    "get_instrument",
    "get_option_chain_instruments",
    "ingest_instruments",
    "instrument_table",
    "load_dhan_limits",
    "parse_scrip_master_csv",
    "resolve_dhan_credentials",
    "resolve_exchange_segment",
    "search_instruments",
    "store_dhan_credentials_dpapi",
]
