"""Long-term investing portfolio management, lot accounting, and reconciliation."""

from __future__ import annotations

from app.investing.analytics import (
    compare_portfolio_to_benchmark,
    compute_account_xirr,
    generate_portfolio_allocation,
    generate_portfolio_cashflows,
    get_security_sector,
)
from app.investing.dividends import (
    DividendIncomeCalendarMonth,
    DividendIncomeView,
    DividendLedger,
    DividendMatchingResult,
    DividendPaymentImportItem,
    DividendRecord,
    DividendStatus,
    dividend_ledger,
)
from app.investing.ledger import HoldingsLedger, holdings_ledger
from app.investing.models import (
    AssetAllocationItem,
    BenchmarkComparisonResult,
    CapitalGainsCategory,
    CashFlowItem,
    CorporateAction,
    CorporateActionType,
    DhanHoldingItem,
    DisposalAllocation,
    DisposalRecord,
    HoldingReconciliationItem,
    HoldingSummary,
    PortfolioAllocationReport,
    PortfolioHoldingsReport,
    ReconciliationReport,
    SectorAllocationItem,
    TaxLot,
    XIRRCalculationResponse,
)
from app.investing.rebalancing import (
    RebalanceAction,
    RebalanceProposal,
    RebalanceProposalItem,
    RebalanceTrigger,
    SIPAllocationItem,
    SIPPlanResult,
    StepUpSIPProjection,
    SubPeriodReturn,
    TWRCalculationResult,
    calculate_time_weighted_return,
    generate_rebalance_proposal,
    plan_sip_instalment,
    project_step_up_sip,
)
from app.investing.reconciliation import (
    import_dhan_holdings_as_initial_lots,
    parse_dhan_holdings_payload,
    reconcile_dhan_holdings,
)
from app.investing.rotation import (
    RotationBacktestResult,
    RotationRebalanceDecision,
    RotationWalkForwardResult,
    RotationWalkForwardWindow,
    SectorConstituentMembership,
    SectorMomentumScore,
    SurvivorshipAuditResult,
    audit_survivorship_bias,
    compute_sector_momentum_scores,
    resolve_pit_sector_constituents,
    run_rotation_walk_forward,
    run_sectoral_momentum_backtest,
)
from app.investing.xirr import (
    XIRRConvergenceError,
    XIRRError,
    XIRRInvalidCashflowsError,
    calculate_xirr,
)

__all__ = [
    "AssetAllocationItem",
    "BenchmarkComparisonResult",
    "CapitalGainsCategory",
    "CashFlowItem",
    "CorporateAction",
    "CorporateActionType",
    "DhanHoldingItem",
    "DisposalAllocation",
    "DisposalRecord",
    "DividendIncomeCalendarMonth",
    "DividendIncomeView",
    "DividendLedger",
    "DividendMatchingResult",
    "DividendPaymentImportItem",
    "DividendRecord",
    "DividendStatus",
    "HoldingReconciliationItem",
    "HoldingSummary",
    "HoldingsLedger",
    "PortfolioAllocationReport",
    "PortfolioHoldingsReport",
    "RebalanceAction",
    "RebalanceProposal",
    "RebalanceProposalItem",
    "RebalanceTrigger",
    "ReconciliationReport",
    "RotationBacktestResult",
    "RotationRebalanceDecision",
    "RotationWalkForwardResult",
    "RotationWalkForwardWindow",
    "SIPAllocationItem",
    "SIPPlanResult",
    "SectorAllocationItem",
    "SectorConstituentMembership",
    "SectorMomentumScore",
    "StepUpSIPProjection",
    "SubPeriodReturn",
    "SurvivorshipAuditResult",
    "TWRCalculationResult",
    "TaxLot",
    "XIRRCalculationResponse",
    "XIRRConvergenceError",
    "XIRRError",
    "XIRRInvalidCashflowsError",
    "audit_survivorship_bias",
    "calculate_time_weighted_return",
    "calculate_xirr",
    "compare_portfolio_to_benchmark",
    "compute_account_xirr",
    "compute_sector_momentum_scores",
    "dividend_ledger",
    "generate_portfolio_allocation",
    "generate_portfolio_cashflows",
    "generate_rebalance_proposal",
    "get_security_sector",
    "holdings_ledger",
    "import_dhan_holdings_as_initial_lots",
    "parse_dhan_holdings_payload",
    "plan_sip_instalment",
    "project_step_up_sip",
    "reconcile_dhan_holdings",
    "resolve_pit_sector_constituents",
    "run_rotation_walk_forward",
    "run_sectoral_momentum_backtest",
]
